### ISSUE TITLE
Add support for specifying specific Lua runtime version

### ISSUE THREAD

**Issue by serozhenka** [cunla/fakeredis-py#287] opened 2024-02-07 08:42 UTC
**Is your feature request related to a problem? Please describe.**
As stated in Redis documentation, the only supported Lua runtime is Lua 5.1. Logically, I would also expect it to work with Lua 5.x, because the new minor versions should be backward-compatible with previous minor versions. However, that is not the case. In Lua 5.2 `unpack` was completely removed and replaced with `table.unpack`. 
So when using Lua with fakeredis, the only available version is `5.4` and in the real-world environment it's `5.1`. Being unable to fix the Lua version and use one of somebody's choice forces to do such a fix to make it working:
```lua
table.unpack = table.unpack or unpack
```

**Describe the solution you'd like**
Probably, a good solution will be to pass Lua version with an environment variable like `FAKEREDIS_LUA_VERSION` and default it to the latest one in case it's not present or lupa doesn't support runtime for this version.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/fakeredis-py/issues/287">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/fakeredis-py/issues/287/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/fakeredis-py/issues/287/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment] 2024-02-07 15:24
Oh, so redis supports only LUA 5.1 while fakeredis supports LUA 5.4.
I think it would be better to default it to 5.1 on fakeredis.

**Comment by cunla** [comment] 2024-02-07 18:32
The issue is with lupa2.0.
If you install lupa 1.14.1 lua 5.1 works fine

**Comment by serozhenka** [comment] 2024-02-07 20:22
Sure, but can it be the feature of the fakeredis to have the ability to specify a specific Lua version or at least have 5.1 as a default one? I don't think lupa maintainers will ever update 1.14.x version.

**Comment by cunla** [comment] 2024-02-07 20:30
A bug should be opened on lupa package. They claim 5.1 is supported in v2.

**Comment by serozhenka** [comment] 2024-02-07 20:43
Sorry, but I don't get it. How does opening an issue ticket in lupa package fix this problem? And what even is the exact problem with lupa?

As stated in lupa documentation:

> The binary wheels include different Lua versions as well as LuaJIT, if supported. **By default, import lupa uses the latest Lua version, but you can choose a specific one via import.**

At the time of writing, the latest version of Lua is 5.4. So when you do
```python
from lupa import LuaRuntime
```
it's the 5.4 is the one that gets used. But in specific Redis scenario, Lua version is fixed to 5.1, so importing the LuaRuntime should like as follows:
```python
from lupa.lua51 import LuaRuntime
```

**Comment by cunla** [comment] 2024-02-07 20:57
So with lupa2 - `from lupa.lua51 import LuaRuntime` does not exist

**Comment by cunla** [comment] 2024-03-23 15:20
I created an issue on lupa, closing this issue.

**Comment by serozhenka** [comment] 2024-03-23 15:55
I also opened the issue some time ago right [here](https://github.com/scoder/lupa/issues/256).
Basically, we'll have it with the next release, so I wouldn't close this issue as you'll still need to import from `lupa.lua51` and not `lupa`

**Comment by cunla** [comment] 2024-03-23 15:58
Good point...

**Closed** 2024-03-24 20:16 UTC
Labels: enhancement, Fund

**Comment by serozhenka** [comment] 2024-03-24 20:19
thank you!
