### ISSUE TITLE
Can't get fake connection when using `USE_REDIS_CACHE`

### ISSUE THREAD

**Issue by RealOrangeOne** [cunla/fakeredis-py#219] opened 2023-07-27 15:04 UTC
**Describe the bug**

When using `django-rq`, configured using `USE_REDIS_CACHE` to point to a cache configuration for Redis, it's not possible to get a fake connection, as it expects either an explicitly configured `HOST` etc, or `URL` variables.

See the [upstream implementation](https://github.com/rq/django-rq/blob/56c123628e3989a8cada3039cd83d0d0d21112b4/django_rq/queues.py#L73). Notably, this should probably also handle both `USE_REDIS_CACHE` and `UNIX_SOCKET_PATH`

**To Reproduce**

1. Configure `django-rq` using `USE_REDIS_CACHE`
2. Attempt to use `get_fake_connection`

**Expected behavior**

I get a fake Redis connection

**Comment by cunla** [comment] 2023-08-07 15:22
Can you share a stacktrace? it is not clear the cause of the issue.

the `from_url` method does not require host/post. In the link you provided in django-rq, it uses from_url.

Perhaps the issue is in django_redis package, I see there is `from django_redis import get_redis_connection as get_redis`

**Comment by cunla** [comment] 2023-08-13 12:50
Closing this. Please reopen with more details

**Closed by cunla** 2023-08-13 12:50 UTC
Labels: bug
