### ISSUE TITLE
Scan in lua script doesn't iterate all keys

### ISSUE THREAD

**Issue by matanper** [cunla/fakeredis-py#95] opened 2022-12-07 22:10 UTC
I'm running the following lua script and it seems the scan command doesn't iterate on all the keys. I've run it with redis-py and it worked as expected 
```
import fakeredis

r = fakeredis.FakeStrictRedis()
for i in range(100):
    r.set(f'key-{i}', i)

script = """
    local cursor = 0
    local seen = {}
    repeat
        local result = redis.call('SCAN', cursor)
        for _,key in ipairs(result[2]) do
            seen[#seen+1] = key
            redis.call('DEL', key)
        end
        cursor = tonumber(result[1])
    until cursor == 0
    return seen
"""

print(len(r.register_script(script)()))  # Expecting here 100, getting 50
print(len(r.keys()))  # Expecting here 0, getting 50
```

**Desktop (please complete the following information):**
 - OS:  Mac
 - python version: 3.8
 - redis-py version: 4.3.4

**Comment by cunla** [comment] 2022-12-09 20:24
The issue is that you are modifying the DB within the script in my opinion.
Check out the note in `_scan(..)` method:
> It also doesn't adhere to the guarantee that every key will be iterated
> at least once even if the database is modified during the scan.
> However, provided the database is not modified, every key will be
> returned exactly once.

**Comment by matanper** [comment] 2022-12-09 21:49
Is that note from `redis-py`?
It contradicts the guarantees in redis documentation:

> A full iteration always retrieves all the elements that were present in the collection from the start to the end of a full iteration. This means that if a given element is inside the collection when an iteration is started, and is still there when an iteration terminates, then at some point SCAN returned it to the user.

**Comment by cunla** [comment] 2022-12-09 22:48
No, that's fakeredis implementation of `SCAN`.

https://github.com/cunla/fakeredis-py/blob/0ef7d4f0fb58c867742b792e25979c31fbdd2c47/fakeredis/_basefakesocket.py#L257-L265

**Comment by matanper** [comment] 2022-12-10 17:02
Got it... I wonder if it's possible to take a snapshot of the db when calling `scan` with cursor = 0

https://github.com/cunla/fakeredis-py/blob/927dcbc4fe49b8cf39809308a9df262dfafe7c9c/fakeredis/commands_mixins/generic_mixin.py#L204-L206

**Comment by cunla** [comment] 2022-12-10 17:23
concurrency in python? :)
I think your suggestion can work, though I would probably put this login in [`_scan(..)` ](https://github.com/cunla/fakeredis-py/blob/0ef7d4f0fb58c867742b792e25979c31fbdd2c47/fakeredis/_basefakesocket.py#L256) so it will support  the various scan commands (`HSCAN`, `SSCAN`, ...) as well.

I added your test to the [lua-error](https://github.com/cunla/fakeredis-py/tree/lua-error) branch, do you mind implementing it and creating a PR for it?

**Comment by matanper** [comment] 2022-12-10 17:35
I was thinking of weird use cases like doing a scan inside a scan... but maybe it's too unique to support

**Comment by cunla** [comment] 2022-12-10 17:54
Based on the [scan](https://redis.io/commands/scan/) documentation:
> ...
> An iteration starts when the cursor is set to 0, and terminates when the cursor returned by the server is 0. The following is an example of SCAN iteration:
> ...
> ## Multiple parallel iterations
> 
> It is possible for an infinite number of clients to iterate the same collection at the same time, as the full state of the iterator is in the cursor, that is obtained and returned to the client at every call. No server side state is taken at all.
>
> ## Terminating iterations in the middle
> 
> Since there is no state server side, but the full state is captured by the cursor, the caller is free to terminate an iteration half-way without signaling this to the server in any way. An infinite number of iterations can be started and never terminated without any issue.

So basically the command should create a snapshot of the list of keys per connection when getting from the connection cursor 0.

Since the `FakeSocket` is created per [`FakeConnection`](https://github.com/cunla/fakeredis-py/blob/master/fakeredis/_server.py#L48-L51) then your suggestion should comply with the Redis standards.

**Comment by matanper** [comment] 2022-12-10 22:07
The `FakeSocket` per connection does solves the parallelism but what do you think should happen in the following case, should it be supported?
```
local cursor = 0
repeat
    local result = redis.call('SCAN', cursor)
    for _,key in ipairs(result[2]) do
        local innerCursor = 0
        repeat
            local setResult = redis.call('SSCAN', key, innerCursor)
            ...
            innerCursor = tonumber(setResult[1])
        until innerCursor == 0
    end
    cursor = tonumber(result[1])
until cursor == 0
```

**Comment by cunla** [comment] 2022-12-11 13:55
Not sure if I get the issue, if cursor is 0 -> create a new keys snapshot.

**Comment by matanper** [comment] 2022-12-11 14:27
I solved the example above by saving the keys snapshot per scan type, but still it won't work for a scan inside a scan

**Comment by M1ha-Shvn** [comment] 2023-01-12 12:26
Catched the same issue as well without lua:  if I have 2 sets with keys A and B the code below will remove only A key:
```
async for key in redis_client.scan_iter(match='*', count=1):
    await redis_client.zremrangebyscore(key, min_score='-inf', max_score='+inf')
 ```

**Comment by cunla** [comment] 2023-01-14 17:10
@matanper would you want to finish your PR?

**Comment by matanper** [comment] 2023-01-14 17:36
> @matanper would you want to finish your PR?

Hey, sorry I don't have time right now, better close and maybe I'll open again when I can

**Comment by cunla** [comment] 2023-01-14 17:37
No worries - I will take over if it is ok with you.

**Comment by matanper** [comment] 2023-01-14 17:56
> No worries - I will take over if it is ok with you.

Of course.
I've also seen this [blog](https://www.freecodecamp.org/news/redis-hash-table-scan-explained-537cc8bb9f52/) about how redis implements the scan, thought it might be interesting to try do it in python

**Comment by cunla** [comment] 2023-05-09 19:37
Hi, I wrote tests demonstrating that keys deleted in the middle of scan do not appear on scan.
I am closing this issue as it looks like all tests pass.

**Closed by cunla** 2023-05-09 19:37 UTC
Labels: bug

**Comment by cunla** [comment] 2023-05-10 00:13
redis updated [the documentation](https://redis.io/commands/scan/) as well :smile:

> Elements that were not constantly present in the collection during a full iteration, may be returned or not: it is undefined.
